#!/usr/bin/env python3
"""Render the full EasyBar product configuration reference from EasyBarKit schema metadata."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def markdown_escape(value: str) -> str:
    """Escape text for use in a Markdown table cell."""
    return value.replace("|", r"\|")


def code(value: str) -> str:
    """Wrap a value as escaped inline Markdown code."""
    escaped = value.replace("`", r"\`")
    return f"`{escaped}`"


def load_catalog(path: Path) -> dict[str, Any]:
    """Load and validate a configuration schema catalog."""
    catalog = json.loads(path.read_text(encoding="utf-8"))
    if catalog.get("schemaVersion") != 1:
        raise SystemExit(f"Unsupported configuration schema version in {path}")
    return catalog


def render(catalog: dict[str, Any]) -> str:
    """Render a configuration catalog as Markdown."""
    lines = [
        "<!--",
        "This file is generated from EasyBarKit's config.schema.json.",
        "Do not edit this file by hand. Update the EasyBarConfigSchema module sources instead.",
        "-->",
        "",
        "# EasyBar Configuration Reference",
        "",
        "Generated from the `EasyBarConfigSchema` module: `ConfigSchema.swift` and the `ConfigSchema*Lines.swift` files.",
        "",
        "Use this page for the complete EasyBar product schema and its built-in defaults.",
        "EasyBar Native uses the same parser with a narrower frontend policy; use its hand-written configuration page for the Native contract.",
        "For EasyBar concepts and usage examples, use the hand-written configuration guides.",
        "",
        "`Not set` means the shipped default config omits that key. The Example column shows a commented value that can be enabled explicitly; the description may also document a derived runtime fallback.",
        "",
    ]

    for section in catalog["sections"]:
        lines.extend(
            [
                f"## `{section['name']}`",
                "",
                "| Key | Default | Example | Description |",
                "| --- | ------- | ------- | ----------- |",
            ]
        )

        for entry in section["entries"]:
            value = code(markdown_escape(entry["value"]))
            if entry["kind"] == "default":
                default_value, example_value = value, "—"
            elif entry["kind"] == "example":
                default_value, example_value = "Not set", value
            else:
                raise SystemExit(f"Unknown configuration entry kind: {entry['kind']}")

            lines.append(
                f"| {code(entry['key'])} | {default_value} | {example_value} | "
                f"{markdown_escape(entry['description'])} |"
            )

        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    """Parse arguments and write the configuration reference."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(load_catalog(args.schema)), encoding="utf-8")
    print(f"Generated configuration reference in {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
